### ISSUE TITLE
Create a dedicated OpenStack client machine

### ISSUE THREAD

**Issue by priteau** [cedadev/jasmin-cluster-as-a-service#1]
The JASMIN OpenStack API is IP white-listed. To access it, we will use a Jasmin VM to run the OpenStack client.

- [x] Provision JASMIN VM instance
- [x] Create accounts for the StackHPC team with their SSH keys
- [x] Install OpenStack client
- [x] Configure environment to interact with the API

OpenStack environment:

    export OS_AUTH_URL=https://kataifi.sweet.jasmin.ac.uk/v3
    export OS_IDENTITY_API_VERSION=3
    export OS_PROJECT_DOMAIN_NAME=jasmin
    export OS_USER_DOMAIN_NAME=jasmin
    export OS_PROJECT_NAME=caastest-U
    export OS_USERNAME=<username>
    export OS_PASSWORD=<password>

**Comment by priteau** [comment]
Connect to the `os-api-client` instance via SSH. You will find an `openrc` file in your home directory.

**Comment by priteau** [comment]
@brtknr @hollysilk @oneswig Please check that you can connect to the VM and use the `openstack` CLI.

**Comment by brtknr** [comment]
Yep, I can confirm that I can connect to the VM and use my OpenStack credentials using this openrc config:

```
export OS_AUTH_URL=https://kataifi.sweet.jasmin.ac.uk/v3

# With the addition of Keystone we have standardized on the term **project**
# as the entity that owns the resources.
export OS_PROJECT_DOMAIN_NAME="jasmin"
unset OS_PROJECT_DOMAIN_ID

export OS_PROJECT_NAME="caastest-U"
export OS_USER_DOMAIN_NAME="jasmin"
if [ -z "$OS_USER_DOMAIN_NAME" ]; then unset OS_USER_DOMAIN_NAME; fi

# unset v2.0 items in case set
unset OS_TENANT_ID
unset OS_TENANT_NAME

# In addition to the owning entity (tenant), OpenStack stores the entity
# performing the action as the **user**.
export OS_USERNAME="brtknr"

# With Keystone you pass the keystone password.
echo "Please enter your OpenStack Password for project $OS_PROJECT_NAME as user $OS_USERNAME: "
read -sr OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT

# If your configuration has multiple regions, we set that information here.
# OS_REGION_NAME is optional and only valid in certain environments.
export OS_REGION_NAME=""
# Don't leave a blank variable, unset it if it was empty
if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi

export OS_INTERFACE=public
export OS_IDENTITY_API_VERSION=3
```

**Comment by brtkwr** [comment]
Yep, I can confirm that with the latest openrc file, I can interface using the openstack CLI :) Thanks @priteau  :)

**Comment by priteau** [comment]
I am recreating a new VM in the caascontrol-U tenant. We will keep the old VM running for now as it has some local data.

**Comment by priteau** [comment]
The new VM has the same name in the `caascontrol-U` tenant. An `openrc` file is in each home directory, configured to interact with the `caastest-U` tenant.

**Comment by priteau** [comment]
I also installed the Heat client in the new VM.
