### ISSUE TITLE
Demonstrate in-place security patching for SLURM

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cluster-as-a-service#11]
We would use the `yum update` approach instead of redeploy from a new image, performed via scheduled jobs on AWX.

**Comment by priteau** [comment]
https://github.com/cedadev/jasmin-appliances/pull/11

**Comment by priteau** [comment]
I haven't worked with AWX yet, will need to figure out how the `update.yml` playbook can be configured as a scheduled job.

**Comment by mkjpryor-stfc** [comment]
@priteau 

Is there any way to use the same playbook for initial installation and updates? That way we can avoid having multiple AWX Job Templates for each cluster type.

For example, for Kubernetes there is one playbook, `cluster_configure.yml`. That playbook checks for an existing installation and runs tasks from either `update.yml` or `install.yml` as appropriate.

**Comment by priteau** [comment]
Good point. We would want to install all updated packages at deployment time anyway, so it makes sense to combine both together. I'll check how we can do this.
