### ISSUE TITLE
Demonstrate in-place upgrade of SLURM

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cluster-as-a-service#12]

**Comment by priteau** [comment]
I found repos of each OpenHPC 1.3 update available at http://ftp.vcu.edu/pub/gnu_linux/openhpc/1.3:/
I modified the stackhpc.openhpc role to set up a set of updates as Yum repos, allowing to test SLURM updates from a specific past version.

**Comment by priteau** [comment]
See https://github.com/cedadev/jasmin-appliances/pull/11
