### ISSUE TITLE
Option to use OpenStack tokens to deploy Heat stacks in Ansible

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cluster-as-a-service#20]

**Comment by brtkwr** [comment]
This is what an example `trustrc` file looks like in contrast to `openrc`.

```
unset OS_USER_DOMAIN_NAME
unset OS_PROJECT_NAME
unset OS_IDENTITY_API_VERSION
unset OS_INTERFACE
unset OS_PROJECT_DOMAIN_NAME
export OS_USERNAME=caasctl
export OS_TRUST_ID=example_trust_id
export OS_USER_ID=example_user_id
export OS_PASSWORD='hidden'
export OS_AUTH_URL=https://kataifi.sweet.jasmin.ac.uk/v3
```

**Comment by mkjpryor-stfc** [comment]
@brtknr So you don't even need a project id or name anymore? I guess it can be pulled out of the trust.

**Comment by mkjpryor-stfc** [comment]
@brtknr And I remember you saying you specifically need `OS_USER_ID` - normally, `OS_USERNAME` is sufficient on it's own.

**Comment by brtkwr** [comment]
@mkjpryor-stfc specifying OS_TRUST_ID removes the need to specify OS_PROJECT_NAME since OS_TRUST_ID is always already tied to a project. If using OS_USERNAME, we additionally need to specify OS_USER_DOMAIN_NAME.

**Comment by brtkwr** [comment]
To create trust, source the `trustor` openrc file and run:

`openstack trust create trustor_uuid service_account_uuid --project project_uuid --impersonate --role=role_uuid`

NOTES:
- specifying project as non UUID gives:
`Could not find project: caastest-U (HTTP 404) (Request-ID: req-9a50fa24-2c2a-4615-923f-81e96f8cb878)`
- specifying user as non UUID gives:
`You are not authorized to perform the requested action: identity:create_trust (HTTP 403) (Request-ID: req-29d8fd35-eae0-46fa-b258-9966cac0af45)`
- specifying role as non UUID gives:
`Could not find role: _member_ (HTTP 404) (Request-ID: req-1565aac2-88ea-4d3f-8333-4eba506e7095)`

To retrieve `trustor_uuid`, I have been running this hack:

`openstack token issue`

**Comment by brtkwr** [comment]
Renaming this task since it does not seem permissive to use delegated trust to create a heat stack which itself uses delegated trust to manage stack components.

However, trust-id will still come useful to pass onto kubernetes cloud-config. OpenStack token seems like a good alternative which seems to allow creation of heat stack as well can generation of trust-id and it has been agreed as a good candidate variable to pass onto AWX instead of username and password.
