### ISSUE TITLE
Remove requirement for StrictHostKeyChecking disabled when using a gateway host

### ISSUE THREAD

**Issue by oneswig** [cedadev/jasmin-cluster-as-a-service#23]
Currently we disable Strict Host Key checking when using ProxyJump ssh connections.

**Comment by oneswig** [comment]
There are several factors that we need to understand better in order to use gateway bastion hosts from an AWX context.

From a command line, we can run commands of the form:

`ssh -o StrictHostKeyChecking=false -o ProxyJump=centos@192.171.139.249 centos@192.168.3.114`

This gets us access to internal hosts from external networks, in one `ssh` hop.

Which pieces of our `ssh` configuration are necessary to make this possible?

### Do we need to use an SSH agent for ProxyJump to work?
We may run `eval $(ssh-agent)` in the terminal on our laptop before starting the session.

### Do we need to use SSH agent forwarding for ProxyJump to work?
In the config file `~/.ssh/config` we might define `ForwardAgent yes`, which enables an ssh agent running on our laptop to manage key authentication all the way down the line.

Instead of doing this, can we copy the *private* SSH key to our login host in the `jasmin-ctrl` tenancy and use it from there?  Similarly, can we use the private key generated for the deployment in the `ansible/` subdirectory?

### Can we fix the SSH keyscan in the jasmin.cluster-infra role to work through a bastion?
Looking at the code in `jasmin.cluster-infra`, can we adapt the invocation of `ssh-keyscan` to make it work with a cluster gateway host?  Does the keyscan need to be delegated to the cluster gateway host, and then do the scanned keys need to be added locally (as before), or on the cluster gateway host, or both?

### Which of these components are necessary but missing when running from an AWX context?

**Comment by oneswig** [comment]
Using `delegate_to` (setting it to `inventory_hostname` when no gateway host is set) appears to work, and all instances of `StrictHostKeyChecking` can be removed.

**Comment by brtkwr** [comment]
Here's the test I ran:
```
+- debug:
+    msg: "{{ lookup('env', 'HOME') }}"

/var/lib/awx

+- debug:
+    msg: "{{ lookup('env', 'HOME') }}"
+  become: yes

/var/lib/awx

+- debug:
+    msg: "{{ lookup('env', 'HOME') }}"
+  delegate_to: "{{ inventory_hostname }}"
+  become: yes

/var/lib/awx

+- local_action: command echo ~
+  register: local_home_dir
+- debug: var=local_home_dir

/var/lib/awx
```
