### ISSUE TITLE
Configure SLURM storage from named storage stack using stack outputs

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cluster-as-a-service#32]
Includes writing a Python module to get the outputs of  a Heat stack without updating the stack.

Storage type and connection params would be available as stack outputs from storage clusters to be consumed by "compute" clusters.

**Comment by oneswig** [comment]
This might do the trick: https://github.com/stackhpc/ansible-role-os-container-infra/blob/master/library/os_stack_facts.py
