### ISSUE TITLE
Method to resize a cluster when the underlying image could have been revoked.

### ISSUE THREAD

**Issue by oneswig** [cedadev/jasmin-cluster-as-a-service#33]
The CentOS base images are updated on a regular basis.  Older versions of the base image are removed from the catalogue when new versions are released.

Images follow a naming convention that includes the date of creation.  For flexibility, it would be good to automate the retrieval of the latest current edition of the base image.

If a cluster was deployed prior to a CentOS image upgrade, resizing it should not result in re-imaging of the entire cluster.  A private image or snapshot based on the base image at creation date should be available to build new compute images.

**Comment by mkjpryor-stfc** [comment]
![jasmin caas decision tree](https://user-images.githubusercontent.com/13452123/53740835-01061f00-3e8d-11e9-9b3c-b9e42588009e.png)
