### ISSUE TITLE
Validate SLURM cluster deployed in cloud tenancy

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-cluster-as-a-service#8]

**Comment by oneswig** [comment]
Validation steps proposed for Slurm cluster:
* Verify that platform users exist on login and compute nodes
* Verify that the network filesystem has been mounted on all clients
* Check for the existence of the munged process (this appears to be a failure pattern so far)
* Check for any failed systemd services.
* Run a simple Slurm job, eg srun -N 2 hostname
* Run a simple MPI job through Slurm, eg IMB-MPI1

**Comment by priteau** [comment]
If possible, test that we can write from a client and read back from another one.
