### ISSUE TITLE
Is the CentOS firewalld service required?

### ISSUE THREAD

**Issue by oneswig** [cedadev/jasmin-cluster-as-a-service#9]
The RAL CentOS software image includes `firewalld`, which we have been working with to ensure that the correct ports are opened, and that services are configured to work within defined ranges of ports that have been opened in anticipation.

Currently, enough ports have been opened to support Slurm cluster management and job launch.  However, firewall configuration to support inter-process communication (eg, OpenMPI) has not been tackled yet.

This might be extraneous work for a Slurm cluster - what is RAL's view on whether the CentOS firewall daemon should be running on login and compute nodes in a Slurm cluster?

**Comment by mkjpryor-stfc** [comment]
My feeling is that we should aim to keep the firewalld support if possible, as there is nothing to stop users attaching a floating IP to any machine and exposing it directly to the Internet. Login nodes should definitely keep it.

**Comment by mkjpryor-stfc** [comment]
Certainly there will never be a template that doesn't include it by default, with only SSH permitted. Given our target users, we have opted for a "secure by default" template. For example, password-based SSH is also disabled.

**Comment by oneswig** [comment]
Agreed.  We've gone with permitting access to all hosts on the subnet of the primary network.

In future if JASMIN wants to build CaaS images that don't use firewalld, we can accommodate that with a few conditionals.
